### ISSUE TITLE
Add Hyperlink to SDS Homepage

### ISSUE THREAD

**Issue by kanak8278** [SDS-Society-for-Data-Science-BIT-Mesra/Data-Science-Summit#33]
- [x] https://datathon.sdsbitmesra.in is a subpage to [https://sdsbitmesra.in](https://sdsbitmesra.in) so add a hyperlink in the navbar which redirects it to [https://sdsbitmesra.in](https://sdsbitmesra.in).

- [x] Also add a hyperlink to the SDS logo (left top in navbar), which redirects to the SDS homepage [https://sdsbitmesra.in](https://sdsbitmesra.in).

**Comment by Rishika-05** [comment]
Working on this issue.
